"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavbarLayout from "./layout/navbar/page";
import { usePathname } from "next/navigation";

import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const showNavbarLayout = pathname != "/";
  console.log(pathname);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>{showNavbarLayout && <NavbarLayout />}</div>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
